// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebVilla.Data;

#nullable disable

namespace WebVilla.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230120132915_AddSeedDataVilla")]
    partial class AddSeedDataVilla
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebVilla.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Occupancy")
                        .HasColumnType("integer");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<int>("Sqft")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedAt = new DateTime(2023, 1, 20, 13, 29, 14, 848, DateTimeKind.Utc).AddTicks(8227),
                            Details = "",
                            ImageUrl = "/Images/Villa.jpeg",
                            Name = "Royal Villa",
                            Occupancy = 1,
                            Rate = 300.0,
                            Sqft = 550,
                            UpdatedAt = new DateTime(2023, 1, 20, 13, 29, 14, 848, DateTimeKind.Utc).AddTicks(8224)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedAt = new DateTime(2023, 1, 20, 13, 29, 14, 848, DateTimeKind.Utc).AddTicks(8232),
                            Details = "",
                            ImageUrl = "/Images/Villa3.jpeg",
                            Name = "Luxury Villa",
                            Occupancy = 1,
                            Rate = 300.0,
                            Sqft = 550,
                            UpdatedAt = new DateTime(2023, 1, 20, 13, 29, 14, 848, DateTimeKind.Utc).AddTicks(8230)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
